{
  imports = [
    ./acme.nix
    ./actualbudget.nix
    ./cartograph.nix
    ./cookbook.nix
    ./fompf.nix
    ./forgejo.nix
    ./headscale.nix
    ./immich.nix
    ./kanidm.nix
    ./minecraft.nix
    ./monitoring
    ./nextcloud.nix
    ./nginx-public.nix
    ./oauth2_proxy.nix
    ./paperless.nix
    ./restic-server.nix
    #./spacebar.nix
    ./syncproxy.nix
    ./vaultwarden.nix
  ];
}
