theme = "gruvbox-dark"
icons = "material-nf"

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
unit = "GB"
interval = 60
warning = 80.0
alert = 90.0
format = "{used;G}/{total;G} ({percentage})"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used;G} /{mem_total;G} ({mem_total_used_percents})"
clickable = false

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
on_click = "exec --no-startup-id alacritty --class floatingTerm,floatingTerm -e nmtui" 
format = "{ssid} ({signal_strength}) | {graph_up} {graph_down}"
interval = 5

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 60
format = "{percentage}"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %I:%M"

